---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: default
spec:
  encryptedData:
    token: AgC4szZ7JgxxqRJfFZeocdKNXIxc3IxULQ4Oa9ok1h9JpMmuG4lK7qSNKv2x4TISE2fb75fgW/Thgj0uRobda+xMd4BkyDGSLYoiU16GmTNmV2gCXJlA41PynrTWeYjIneJQEoskEJ3fYBz0VJe5qlmDwCf353UCh2+4S9WzHPdqmmS0I83JitqjTfThONiP8rFL/YPyBHnnPbaKePVfCgorZW7mf7iYjW/S0M8xvomKmGeV+OEBx5AQzWZmj+iC4Fu8orCPjaRrkur6AMvlx4OfudE5fpdm9wRc6iJfiwtFTNtkwbvnJznHeucG+RwnLwN+0E82TLBW12Lc2bqGtaerteoauGxunv+ZX5/1UGVsaUl4P4VFKWYoVwlptpRff1aynEafP3tk+EePaU2FTZvsH6q9OTVegGPuX++w4mFSm3SpZM/4cQl7r3/7u9T1oooMQWCQN9r8TqHnpcF+4r/6AJjCMdD3i7W7+DiLsR/gI5NE6QeucPYjRhf+5rOpU/jYfa8G5itaRt8wrTQZuq/a/G+OvbeMGZ+fBIUWhHrSXFmfF3OyDUquy1BvuVgBoZfihRtijwTKppRuC9n50u/HbM3FECZwKcwL1gDol7lC2VkIbKRH7l+kXO4eN7GiHemPX2EeF/ukpebrlNbyJt8s0MDcx38VdtMJHjmrbbXK7aQvDyKVE/3lXX5pcQnMBLfXcCBhIqDy5hypDakEH5N9RnFCxqGxJDkypLYMgTh94RZ5rV1ZmCKm
  template:
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: default
    type: Opaque